#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include"hello.h"

int*init_con=NULL;//初始化变量存储位置
intn=100;//停车场车位
intten_mun;//十分钟的价钱
inthfh_mun;//半小时的价钱
inthou_mun;//一小时的价钱

intread_f_num();
voidinit_sys(char**plc);//初始化系统
voidCar_Com();//车来了，需要车牌号，会为车牌号分配对应的停车位
voidCar_Out();//车走了
voidCar_Wer();//车在哪


//
intmain()
{
//while(NOW!=100)
//{
//He_init();
//}
//puts("欢迎管理员");
//system("pause");
//IsRight();
//He_init();
char**park;
init_sys(park);
return0;
}

intread_f_num(FILE*fp)
{
chars[100];
intnum=0;
fgets(s,100,fp);
//printf("%s\t",s);
intn=strlen(s);
if(s[0]!='\n')
{
//if(s[n-1]=='\n')n-=1;
//printf("thisis%d:\t",n);
for(inti=0;i<=n;i++,num*=10)
{
if(s[i]<='9'&&s[i]>='0')
{
num+=(s[i]-'0');
//printf("the%dis%c\t",i,s[i]);
}
elsenum/=10;
}
num/=10;
}
//printf("%d\n",num);
returnnum;
}

voidinit_sys(char**plc)
{
FILE*sys=NULL;
if((sys=fopen(".\\data\\system","r"))==NULL)
{
printf("Cannotopenwritefile\n");
exit(0);
}
init_con=(int*)malloc(sizeof(int)*6);
for(inti=0;i<6;i++)
{
init_con[i]=read_f_num(sys);
}
user_len=init_con[0];
paswd_len=init_con[1];
n=init_con[2];
ten_mun=init_con[3];
hfh_mun=init_con[4];
hou_mun=init_con[5];
printf("%d\n",user_len);
fclose(sys);
}

