CC="gcc"
# # all:停车管理系统.exe clean
# allo = main.o mak_list.o
# allc = main.c mak_list.c

# 停车管理系统.exe:allo
# 	$(CC) $@ $<

# allo:allc
# 	$(CC)-o$@-c$<

# # right.o:right.c
# # 	$(CC)-o$@-c$<

# clean:
# 	rm-f*.o

main:main.c
	$(CC) main.c -o main
